services:
  - type: web
    name: proyect-inventario-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_USER
        value: YOUR_DB_USER
      - key: DB_PASSWORD
        value: YOUR_DB_PASSWORD
      - key: DB_NAME
        value: Proyect_inventario
